name: update assets/readme

on:
  push:
    branches:
      - main

jobs:
  update:
    if: ${{ !startsWith(github.event.head_commit.message, 'Merge pull request') }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: update on wordpress
        uses: 10up/action-wordpress-plugin-asset-update@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: privacy-embed
